# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsSwiftUI-mvvm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'RealmSwift', '~> 3.20.0'
pod 'Alamofire'
pod 'AlamofireObjectMapper', '~> 5.2'
pod 'SDWebImage'



end
